name: settings
description: Settings for all library
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  net:
    git: https://github.com/lamtx/net.git
  shared_preferences: any