name: settings
description: Settings for all library
version: 0.0.1
publish_to: none

environment:
  sdk: ^2.12.0

dependencies:
  meta: any
  net:
    git: https://github.com/lamtx/net.git
  shared_preferences: ^2.0.1